#Author: Reuben Johnston
#Description: Action to build project latex into pdf files when a release tag with formatl '*.*' is created.

name: Build LaTeX document
on:
  push:
    tags:
      - '*.*'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Compile LaTeX document 1
        uses: xu-cheng/latex-action@v3
        with:
          root_file: curated_list_of_infamous_malware_reuben_johnston.tex

      - name: Compile LaTeX document 2
        uses: xu-cheng/latex-action@v3
        with:
          root_file: curated_list_of_infamous_attacks_reuben_johnston.tex

      - name: Upload Release Asset 1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./curated_list_of_infamous_malware_reuben_johnston.pdf
          asset_name: curated_list_of_infamous_malware_reuben_johnston.pdf
          asset_content_type: pdf

      - name: Upload Release Asset 2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./curated_list_of_infamous_attacks_reuben_johnston.pdf
          asset_name: curated_list_of_infamous_attacks_reuben_johnston.pdf
          asset_content_type: pdf
